### PR TITLE
Fixed documentation for 0.11.2, this fixes cpp-netlib/cpp-netlib#581

### PR DESCRIPTION
**Pull request by susnux**
* Fixed hello_world_server example
* Fixed url of rapidjson in twitter example

### CODE REVIEW

**Comment by deanberris** [comment]
Can you make the change to the documentation sources instead of the generated documentation? This should be in `libs/network/doc/`, and we're generating it using Sphinx. I'm also preparing for a 0.12 release which does make a few more changes to the documentation, simplifying a lot of it.

Do you think that would be better @susnux? Or is this the result of that already?

**Comment by susnux** [comment]
Ah ok I should push it to the 0.11-devel branch?
https://github.com/cpp-netlib/cpp-netlib/tree/0.11-devel

The result should be the same (I also modified the sources and generated this with Sphinx) ;-)

**Comment by deanberris** [comment]
I think sending it to the master branch would be best, as releasing 0.12 should happen pretty soon (I'm mostly going through the documentation, and should be ready to package up/tag a 0.12.0 release candidate on master). Then we can get the 0.12 documentation up on the website with these changes.

**Comment by susnux** [comment]
ok I have send it there:
https://github.com/cpp-netlib/cpp-netlib/pull/584

**Comment by deanberris** [comment]
Thanks @susnux! I'll merge this in anyway to update the website -- I think it's worth doing now.

**Pull request merged**
